#!/bin/bash

###################
# Option Defailts #
###################
pages=false
verbose=0

###################
# Version & Usage #
###################
VERSION="0.0.0"
USAGE="
$(basename $0) version $VERSION

Update sheet attributes in one or more schematics

usage:

    $(basename $0) [options] schematic [schematic2 ...]
    $(basename $0) --pages *.sch  # update page attrs for all sch files in dir

options:

    --checkedby VAL             set checkedby to VAL
    --checkedcomment VAL        set checkedcomment attr 
    --checkeddate VAL           set checkeddate attr 
    --drawnby VAL               set drawnby attr 
    --drawncomment VAL          set drawncomment attr 
    --drawndate VAL             set drawndate attr (def: file mtime)
    --filename VAL              set filename attr 
    --mfgapprovedby VAL         set mfgapprovedby to VAL
    --mfgapprovedcomment VAL    set mfgapprovedcomment attr 
    --mfgapproveddate VAL       set mfgapproveddate attr 
    --pages VAL                 set pagenumber and pagetotal attrs
    --project VAL               set project attr 
    --revision VAL              set revision attr 
    --title VAL                 set title attr 

    -v, --verbose   increase verbosity
    -h, --help      print this message and exit
    --              options terminator

description of supported sheet attributes

    sheet-project - project name (same for all schematics)
    sheet-title - schematic's title
    sheet-filename - schematics filename
    sheet-revision - project revision number (same for all schematics)
    sheet-pagenumber - schematic's page number
    sheet-pagetotal - number of schematics in project
    sheet-drawnby - schematic's author
    sheet-drawndate - schematics last modification
    sheet-drawncomment - comment about schematic drawing
    sheet-checkedby - schematic checker's name
    sheet-checkeddate - date schematic was checked
    sheet-checkedcomment - comment from checking
    sheet-mfgapprovedby - approved for manufacturing by
    sheet-mfgapproveddate - date for approval
    sheet-mfgapprovedcomment - comment about approval
"

#################
# Parse Options #
#################
while [[ $1 == -* ]]; do
    case $1 in
        --checkedby)
            checkedby="$2"
            shift  # past value
            ;;
        --checkedcomment)
            checkedcomment="$2"
            shift  # past value
            ;;
        --checkeddate)
            checkeddate="$2"
            shift  # past value
            ;;
        --drawnby)
            drawnby="$2"
            shift  # past value
            ;;
        --drawncomment)
            drawncomment="$2"
            shift  # past value
            ;;
        --drawndate)
            drawndate="$2"
            shift  # past value
            ;;
        --mfgapprovedby)
            mfgapprovedby="$2"
            shift  # past value
            ;;
        --mfgapprovedcomment)
            mfgapprovedcomment="$2"
            shift  # past value
            ;;
        --mfgapproveddate)
            mfgapproveddate="$2"
            shift  # past value
            ;;
        --pages)
            pages=true
            ;;
        --project)
            project="$2"
            shift  # past value
            ;;
        --rev)
            revision="$2"
            shift  # past value
            ;;
        --title)
            title="$2"
            shift  # past value
            ;;
        -v|--verbose)
            ((verbose+=1))
            # do not shift again!
            ;;
        -h|--help)
            echo "$USAGE"
            exit
            ;;
        --)
            shift
            break
            ;;
        *)
            >&2 echo "$(basename $0): unknown option $1" \
                "(run '$(basename $0) --help' for available options)"
            exit 1
    esac
    shift
done
# all options have been shifted out, so just arguments are left in $@

if [ $# -lt 1 ]; then
    >&2 echo "no files to update, exiting"
    exit 1
fi
for f in "$@"; do
    if ! [ -f $f ]; then
        >&2 echo "$f is not a regular file, exiting"
        exit 1
    fi
done

###############
# Main Script #
###############

i=1
numfiles=$#
for f in "$@"; do
    # if date not given, set to file mtime
    test -z "$drawndate" && drawndate=$(stat --printf='%y' $f | cut -d' ' -f1)
    sed -i -f <(
        echo "s/\(sheet-filename\)=.*/\1=$(basename $f)/"
        echo "s/\(sheet-drawndate\)=.*/\1=$drawndate/"
        test -z "$checkedby" \
            || echo "s/\(sheet-checkedby\)=.*/\1=$checkedby/"
        test -z "$checkedcomment" \
            || echo "s/\(sheet-checkedcomment\)=.*/\1=$checkedcomment/"
        test -z "$checkeddate" \
            || echo "s/\(sheet-checkeddate\)=.*/\1=$checkeddate/"
        test -z "$drawnby" \
            || echo "s/\(sheet-drawnby\)=.*/\1=$drawnby/"
        test -z "$drawncomment" \
            || echo "s/\(sheet-drawncomment\)=.*/\1=$drawncomment/"
        test -z "$mfgapprovedby" \
            || echo "s/\(sheet-mfgapprovedby\)=.*/\1=$mfgapprovedby/"
        test -z "$mfgapprovedcomment" \
            || echo "s/\(sheet-mfgapprovedcomment\)=.*/\1=$mfgapprovedcomment/"
        test -z "$mfgapproveddate" \
            || echo "s/\(sheet-mfgapproveddate\)=.*/\1=$mfgapproveddate/"
        test $pages = true \
            && echo "s/\(sheet-pagenumber\)=.*/\1=$i/"
        test $pages = true \
            && echo "s/\(sheet-pagetotal\)=.*/\1=$numfiles/"
        test -z "$project" \
            || echo "s/\(sheet-project\)=.*/\1=$project/"
        test -z "$revision" \
            || echo "s/\(sheet-revision\)=.*/\1=$revision/"
        test -z "$title" \
            || echo "s/\(sheet-title\)=.*/\1=$title/"
    ) $f
    ((i+=1))
done
